name: deployment-ci-action

on:
  push:
    tags:
      - '[0-99].[0-99].[0-99]'

env:
  PYTHON_VERSION: "3.11.2"

jobs:
  main-ci-action:
    uses: ./.github/workflows/main.yml
  deployment-ci-action:
    needs: [tests] # require tests to pass before deploy runs
    runs-on: ubuntu-latest

    permissions:
      # required to be able to push sphinx doc
      # to the branch 'gh-pages'
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install package and build dependencies
        run: |
          pip install .
          pip install -r build-requirements.txt
          pip install twine

      - name: Run e2e tests
        run: .github/workflows/e2e.sh

      - name: Install dev dependencies
        run: pip install -r dev-requirements.txt

      - name: Build PyPI (source) package
        if: success()  &&   startsWith(github.ref, 'refs/tags') #TODO should be main
        shell: bash -l {0}
        run: |
          rm -rf ./dist
          python setup.py sdist
          twine check dist/*

      - name: Deploy package to TestPyPI
        if: success()  &&  startsWith(github.ref, 'refs/tags') #TODO should be main
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          package_version: ${{ github.ref_name }}
