name: main-ci-action

on:
  push:
    branches: ["**"]      
  pull_request:
    branches: ["dev"]

env:
  PYTHON_VERSION: "3.11.2"

jobs:
  main-ci-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: python -m unittest discover -v
      - name: Run e2e tests
        run: python main.py
